# Generated by Django 5.2.5 on 2025-08-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
